-- Author:  Christopher Mortiemr
-- Date:    2020-06-24
-- Desc:    Concept for how to store data in a database to underpin model

DROP TABLE IF EXISTS mortimer_workforce.LOCATION;
DROP TABLE IF EXISTS mortimer_workforce.LOCATION_TYPE;
DROP TABLE IF EXISTS mortimer_workforce.GP_FELLOW;
DROP TABLE IF EXISTS mortimer_workforce.GP_TRAINEE;
DROP TABLE IF EXISTS mortimer_workforce.PERSON_AGENT;
DROP TABLE IF EXISTS mortimer_workforce.PROBABILITY;
DROP TABLE IF EXISTS mortimer_workforce.PROBABILITY_TYPE;
DROP TABLE IF EXISTS mortimer_workforce.SCENARIO;

-- Location Type
CREATE TABLE mortimer_workforce.LOCATION_TYPE (
	LOCATION_TYPE_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , LOCATION_TYPE_NAME VARCHAR(100)
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
;
-- Location
CREATE TABLE mortimer_workforce.LOCATION (
	LOCATION_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , LOCATION_TYPE_ID INT(11)
    , LOCATION_NAME VARCHAR(100)
	, GEO GEOMETRY
    , CONSTRAINT FK_LOCATION_LOCATION_TYPE_ID FOREIGN KEY (`LOCATION_TYPE_ID`) 
		REFERENCES LOCATION_TYPE(`LOCATION_TYPE_ID`)
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
;
-- Person Agent
CREATE TABLE mortimer_workforce.PERSON_AGENT (
	PERSON_AGENT_ID INT(11) NOT NULL AUTO_INCREMENT
	, DATE_OF_BIRTH DATE
    , SEX CHAR(1)
    , LOCATION_ID int(11)
	, PRIMARY KEY (`PERSON_AGENT_ID`)
    , CONSTRAINT FK_PERSON_AGENT_LOCATION_ID FOREIGN KEY (`LOCATION_ID`) 
		REFERENCES LOCATION (`LOCATION_ID`) 
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci
;
-- GP Fellows
CREATE TABLE mortimer_workforce.GP_FELLOW (
	GP_FELLOW_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
	, PERSON_AGENT_ID INT(11) NOT NULL
    , YEAR_FELLOWED INT(11)
    , IS_IMG_FLAG CHAR(1)
    , CONSTRAINT FK_GP_FELLOW_PERSON_AGENT FOREIGN KEY (`PERSON_AGENT_ID`) 
		REFERENCES PERSON_AGENT (`PERSON_AGENT_ID`) 
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci
;
-- GP Trainees
CREATE TABLE mortimer_workforce.GP_TRAINEE (
	GP_FELLOW_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , PERSON_AGENT_ID INT(11)
    , YEAR_STARTED_TRAINING INT(11)
    , CONSTRAINT FK_GP_TRAINEE_PERSON_AGENT_ID FOREIGN KEY (`PERSON_AGENT_ID`) 
		REFERENCES PERSON_AGENT(`PERSON_AGENT_ID`)
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci
;
-- Probability Type
CREATE TABLE mortimer_workforce.PROBABILITY_TYPE (
	PROBABILITY_TYPE_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , PROBABILITY_TYPE_NAME VARCHAR(100)
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
;
-- Probability
CREATE TABLE mortimer_workforce.PROBABILITY (
	PROBABILITY_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , PROBABILITY_TYPE_ID INT(11)
    , APPLIED_TO_AGENTS JSON
    , PROBABILITY DECIMAL(14,9)
    , CONSTRAINT FK_PROBABILITY_PROBABILITY_TYPE_ID FOREIGN KEY (`PROBABILITY_TYPE_ID`) 
		REFERENCES PROBABILITY_TYPE(`PROBABILITY_TYPE_ID`)
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
;
-- Scenario
CREATE TABLE mortimer_workforce.SCENARIO (
	SCENARIO_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY
    , SCENARIO_NAME VARCHAR(100)
    , HEADSUPP_USER_ID INT(11)
    , SCENARIO_PARAMETERS JSON
)
AUTO_INCREMENT=1 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
;